In [141]:
!pip install panda
!pip install pandas

In [142]:
!pip install sklearn

In [143]:
!pip install numpy

In [144]:
!pip install matplotlib

In [145]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier


In [146]:
treino = pd.read_csv('Treino.csv')

In [147]:
teste = pd.read_csv('Teste.csv')

In [148]:
treino.head()


udi product_id type  air_temperature_k  process_temperature_k  \
0    1     M14860    M              298.1                  308.6   
1    2     L47181    L              298.2                  308.7   
2    5     L47184    L              298.2                  308.7   
3    6     M14865    M              298.1                  308.6   
4    7     L47186    L              298.1                  308.6   

   rotational_speed_rpm  torque_nm  tool_wear_min failure_type  
0                  1551       42.8              0   No Failure  
1                  1408       46.3              3   No Failure  
2                  1408       40.0              9   No Failure  
3                  1425       41.9             11   No Failure  
4                  1558       42.4             14   No Failure

In [149]:
teste.head()


udi product_id type  air_temperature_k  process_temperature_k  \
0   446     L47625    L              297.5                  308.6   
1  7076     L54255    L              300.7                  310.5   
2  1191     L48370    L              297.2                  308.4   
3  2618     L49797    L              299.4                  309.1   
4  5067     L52246    L              304.1                  313.1   

   rotational_speed_rpm  torque_nm  tool_wear_min  
0                  1793       26.7             70  
1                  1536       47.4            192  
2                  1460       42.1             41  
3                  1670       35.9             68  
4                  1550       30.9              9

In [150]:
labelencoder = LabelEncoder()
for i in treino.select_dtypes(include ='object'):
        treino[i] = labelencoder.fit_transform(treino[i])

In [151]:
labelencoder = LabelEncoder()
for i in teste.select_dtypes(include ='object'):
        teste[i] = labelencoder.fit_transform(teste[i])

In [152]:
teste

udi  product_id  type  air_temperature_k  process_temperature_k  \
0      446         427     1              297.5                  308.6   
1     7076        1742     1              300.7                  310.5   
2     1191         577     1              297.2                  308.4   
3     2618         859     1              299.4                  309.1   
4     5067        1362     1              304.1                  313.1   
...    ...         ...   ...                ...                    ...   
3328  5554        1451     1              302.5                  311.9   
3329  6961        1720     1              300.7                  311.0   
3330  6914        1708     1              300.8                  311.2   
3331  5510        1443     1              302.8                  312.2   
3332  3066        2623     2              300.1                  309.2   

      rotational_speed_rpm  torque_nm  tool_wear_min  
0                     1793       26.7             70  
1                     1536       47.4            192  
2                     1460       42.1             41  
3                     1670       35.9             68  
4                     1550       30.9              9  
...                    ...        ...            ...  
3328                  1306       59.7            172  
3329                  1413       52.0             91  
3330                  1481       38.5            181  
3331                  1509       36.5             52  
3332                  1687       27.7             95  

[3333 rows x 8 columns]

In [153]:
treino.head()

udi  product_id  type  air_temperature_k  process_temperature_k  \
0    1        4680     2              298.1                  308.6   
1    2         658     1              298.2                  308.7   
2    5         659     1              298.2                  308.7   
3    6        4681     2              298.1                  308.6   
4    7         660     1              298.1                  308.6   

   rotational_speed_rpm  torque_nm  tool_wear_min  failure_type  
0                  1551       42.8              0             1  
1                  1408       46.3              3             1  
2                  1408       40.0              9             1  
3                  1425       41.9             11             1  
4                  1558       42.4             14             1

In [154]:
x = treino.iloc[:,2:8]

In [155]:
y = treino.iloc[:,-1]

In [156]:
y_test = teste.iloc[:,2:8]

In [157]:
x

type  air_temperature_k  process_temperature_k  rotational_speed_rpm  \
0        2              298.1                  308.6                  1551   
1        1              298.2                  308.7                  1408   
2        1              298.2                  308.7                  1408   
3        2              298.1                  308.6                  1425   
4        1              298.1                  308.6                  1558   
...    ...                ...                    ...                   ...   
6662     1              298.8                  308.3                  1634   
6663     2              298.8                  308.4                  1604   
6664     0              298.9                  308.4                  1632   
6665     0              299.0                  308.7                  1408   
6666     2              299.0                  308.7                  1500   

      torque_nm  tool_wear_min  
0          42.8              0  
1          46.3              3  
2          40.0              9  
3          41.9             11  
4          42.4             14  
...         ...            ...  
6662       27.9             12  
6663       29.5             14  
6664       31.8             17  
6665       48.5             25  
6666       40.2             30  

[6667 rows x 6 columns]

In [158]:
x_treinamento, x_teste, y_treinamento, y_teste = train_test_split(x, y, test_size=0.3, random_state=0)

In [159]:
print(x_treinamento.shape)
print(x_teste.shape)
print(y_treinamento.shape)
print(y_teste.shape)

(4666, 6)
(2001, 6)
(4666,)
(2001,)


In [160]:
floresta = RandomForestClassifier(n_estimators = 500 , random_state=0)
floresta.fit(x_treinamento, y_treinamento)

RandomForestClassifier(n_estimators=500, random_state=0)

In [161]:
previsoes = floresta.predict(x_teste)

print(previsoes)


[1 1 1 ... 1 1 1]


In [162]:
confusao = confusion_matrix(y_teste,previsoes)
print(confusao)

[[  10    8    0    0    0    0]
 [   4 1926    0    3    0    0]
 [   1   11    3    0    0    0]
 [   0    4    2   10    0    0]
 [   0    5    0    0    0    0]
 [   0   14    0    0    0    0]]


In [163]:
taxa_acerto = accuracy_score(y_teste,previsoes)
print(taxa_acerto)

0.9740129935032483


In [164]:
predict = floresta.predict(y_test)

In [165]:
predict

array([1, 1, 1, ..., 1, 1, 1])

In [166]:
pred

0
0     1
1     1
2     1
3     1
4     1
...  ..
3328  1
3329  1
3330  1
3331  1
3332  1

[3333 rows x 1 columns]

In [167]:
row_num = pd.DataFrame(teste.iloc[:,0])

In [168]:
row_num

udi
0      446
1     7076
2     1191
3     2618
4     5067
...    ...
3328  5554
3329  6961
3330  6914
3331  5510
3332  3066

[3333 rows x 1 columns]

In [169]:
pd.concat([row_num,pred],axis = 1)

udi  0
0      446  1
1     7076  1
2     1191  1
3     2618  1
4     5067  1
...    ... ..
3328  5554  1
3329  6961  1
3330  6914  1
3331  5510  1
3332  3066  1

[3333 rows x 2 columns]

In [170]:
Tabela = pd.concat([row_num,pred],axis = 1)

In [171]:
Tabela.rename(columns={'udi':'Row Number','0':'Predict'},inplace=True)

In [172]:
Tabela

Row Number  0
0            446  1
1           7076  1
2           1191  1
3           2618  1
4           5067  1
...          ... ..
3328        5554  1
3329        6961  1
3330        6914  1
3331        5510  1
3332        3066  1

[3333 rows x 2 columns]

In [173]:
labelencoder = LabelEncoder()
for i in pred.select_dtypes(include ='int'):
        pred[i] = labelencoder.fit_transform(pred[i])

In [174]:
Tabela

Row Number  0
0            446  1
1           7076  1
2           1191  1
3           2618  1
4           5067  1
...          ... ..
3328        5554  1
3329        6961  1
3330        6914  1
3331        5510  1
3332        3066  1

[3333 rows x 2 columns]

In [175]:
Tabela.to_csv('Dados.csv')