In [211]:
!pip install panda
!pip install pandas

In [212]:
!pip install sklearn

In [213]:
!pip install numpy

In [214]:
!pip install matplotlib

In [215]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier


In [217]:
treino = pd.read_csv('Treino.csv', sep=',')

In [223]:
teste = pd.read_csv('Teste.csv', sep=',')

In [224]:
treino


udi product_id type  air_temperature_k  process_temperature_k  \
0         1     M14860    M              298.1                  308.6   
1         2     L47181    L              298.2                  308.7   
2         5     L47184    L              298.2                  308.7   
3         6     M14865    M              298.1                  308.6   
4         7     L47186    L              298.1                  308.6   
...     ...        ...  ...                ...                    ...   
6662   9995     L57174    L              298.8                  308.3   
6663   9996     M24855    M              298.8                  308.4   
6664   9997     H39410    H              298.9                  308.4   
6665   9999     H39412    H              299.0                  308.7   
6666  10000     M24859    M              299.0                  308.7   

      rotational_speed_rpm  torque_nm  tool_wear_min failure_type  
0                     1551       42.8              0   No Failure  
1                     1408       46.3              3   No Failure  
2                     1408       40.0              9   No Failure  
3                     1425       41.9             11   No Failure  
4                     1558       42.4             14   No Failure  
...                    ...        ...            ...          ...  
6662                  1634       27.9             12   No Failure  
6663                  1604       29.5             14   No Failure  
6664                  1632       31.8             17   No Failure  
6665                  1408       48.5             25   No Failure  
6666                  1500       40.2             30   No Failure  

[6667 rows x 9 columns]

In [225]:
teste



udi product_id type  air_temperature_k  process_temperature_k  \
0      446     L47625    L              297.5                  308.6   
1     7076     L54255    L              300.7                  310.5   
2     1191     L48370    L              297.2                  308.4   
3     2618     L49797    L              299.4                  309.1   
4     5067     L52246    L              304.1                  313.1   
...    ...        ...  ...                ...                    ...   
3328  5554     L52733    L              302.5                  311.9   
3329  6961     L54140    L              300.7                  311.0   
3330  6914     L54093    L              300.8                  311.2   
3331  5510     L52689    L              302.8                  312.2   
3332  3066     M17925    M              300.1                  309.2   

      rotational_speed_rpm  torque_nm  tool_wear_min  
0                     1793       26.7             70  
1                     1536       47.4            192  
2                     1460       42.1             41  
3                     1670       35.9             68  
4                     1550       30.9              9  
...                    ...        ...            ...  
3328                  1306       59.7            172  
3329                  1413       52.0             91  
3330                  1481       38.5            181  
3331                  1509       36.5             52  
3332                  1687       27.7             95  

[3333 rows x 8 columns]

In [226]:
labelencoder = LabelEncoder()
for i in treino.select_dtypes(include ='object'):
        treino[i] = labelencoder.fit_transform(treino[i])

In [227]:
labelencoder = LabelEncoder()
for i in teste.select_dtypes(include ='object'):
        teste[i] = labelencoder.fit_transform(teste[i])

In [228]:
teste.rename(columns = {'udi': 'RowNumber'}, inplace = True)

In [229]:
teste

RowNumber  product_id  type  air_temperature_k  process_temperature_k  \
0           446         427     1              297.5                  308.6   
1          7076        1742     1              300.7                  310.5   
2          1191         577     1              297.2                  308.4   
3          2618         859     1              299.4                  309.1   
4          5067        1362     1              304.1                  313.1   
...         ...         ...   ...                ...                    ...   
3328       5554        1451     1              302.5                  311.9   
3329       6961        1720     1              300.7                  311.0   
3330       6914        1708     1              300.8                  311.2   
3331       5510        1443     1              302.8                  312.2   
3332       3066        2623     2              300.1                  309.2   

      rotational_speed_rpm  torque_nm  tool_wear_min  
0                     1793       26.7             70  
1                     1536       47.4            192  
2                     1460       42.1             41  
3                     1670       35.9             68  
4                     1550       30.9              9  
...                    ...        ...            ...  
3328                  1306       59.7            172  
3329                  1413       52.0             91  
3330                  1481       38.5            181  
3331                  1509       36.5             52  
3332                  1687       27.7             95  

[3333 rows x 8 columns]

In [230]:
treino.head()

udi  product_id  type  air_temperature_k  process_temperature_k  \
0    1        4680     2              298.1                  308.6   
1    2         658     1              298.2                  308.7   
2    5         659     1              298.2                  308.7   
3    6        4681     2              298.1                  308.6   
4    7         660     1              298.1                  308.6   

   rotational_speed_rpm  torque_nm  tool_wear_min  failure_type  
0                  1551       42.8              0             1  
1                  1408       46.3              3             1  
2                  1408       40.0              9             1  
3                  1425       41.9             11             1  
4                  1558       42.4             14             1

In [231]:
x = pd.DataFrame(treino.iloc[:,-2])

In [232]:
y = pd.DataFrame(treino.iloc[:,-1])

In [248]:
y_test = pd.DataFrame(teste.iloc[:,-1])

In [259]:
x_treinamento, x_teste, y_treinamento, y_teste = train_test_split(x, y, test_size=0.3, random_state=0)

In [260]:
print(x_treinamento.shape)
print(x_teste.shape)
print(y_treinamento.shape)
print(y_teste.shape)

(4666,)
(2001,)
(4666,)
(2001,)


In [261]:
floresta = RandomForestClassifier(n_estimators = 100, random_state=0)
floresta.fit(x_treinamento, y_treinamento)

ValueError: Expected 2D array, got 1D array instead:
array=[ 58.  72. 201. ... 147.  41.  85.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [246]:
previsoes = floresta.predict(x_teste)

print(previsoes)


NotFittedError: This RandomForestClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [204]:
confusao = confusion_matrix(y_teste,previsoes)
print(confusao)

[[   6    5    0    0    0    0]
 [   4 1283    1    2    0    0]
 [   1    5    4    0    0    0]
 [   0    3    1    9    0    0]
 [   0    2    0    0    0    0]
 [   0    8    0    0    0    0]]


In [205]:
taxa_acerto = accuracy_score(y_teste,previsoes)
print(taxa_acerto)

0.9760119940029985


In [206]:
predict = floresta.predict(y_test)

In [207]:
predict

array([3, 3, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [208]:
pred = pd.DataFrame(predict)

In [209]:
pred.rename(columns = {0:'Predicted'}, inplace = True)

In [210]:
pred

Predicted
0           3
1           3
2           3
3           3
4           1
..        ...
58          3
59          3
60          3
61          3
62          3

[63 rows x 1 columns]

In [129]:
row_num = pd.DataFrame(teste.iloc[:,0:1])

In [1]:
pd.concat([row_num,pred],axis = 1)

NameError: name 'pd' is not defined

In [2]:
Tabela = pd.concat([row_num,pred],axis = 1)

NameError: name 'pd' is not defined

In [96]:
Tabela

RowNumber  Predicted
0         161          2
1         162          3
2         250          3
3         328          3
4         747          3
5         927          2
6        1086          3
7        1168          2
8        1420          2
9        1584          3
10       1596          2
11       2332          3
12       2333          2
13       2495          3
14       2503          3
15       2582          3
16       2859          3
17       3267          3
18       3529          2
19       3685          3
20       3936          2
21       4033          3
22       4118          3
23       4977          3
24       5062          2
25       5220          2
26       5400          2
27       5401          2
28       5489          3
29       5735          2
30       6160          3
31       6256          3
32       6498          3
33       6674          3
34       6925          3
35       7168          2
36       7510          2
37       7594          2
38       7757          3
39       7760          3
40       8027          3
41       8193          2
42       8438          2
43       8609          2
44       9017          3
45       9415          2
46       9654          3
47       9655          2
48       9664          3
49       9665          2
50       9668          2
51       9823          3

In [97]:
labelencoder = LabelEncoder()
for i in pred.select_dtypes(include ='int'):
        pred[i] = labelencoder.fit_transform(pred[i])

In [98]:
Tabela = Tabela.set_index('RowNumber')


In [99]:
Tabela

Predicted
RowNumber           
161                2
162                3
250                3
328                3
747                3
927                2
1086               3
1168               2
1420               2
1584               3
1596               2
2332               3
2333               2
2495               3
2503               3
2582               3
2859               3
3267               3
3529               2
3685               3
3936               2
4033               3
4118               3
4977               3
5062               2
5220               2
5400               2
5401               2
5489               3
5735               2
6160               3
6256               3
6498               3
6674               3
6925               3
7168               2
7510               2
7594               2
7757               3
7760               3
8027               3
8193               2
8438               2
8609               2
9017               3
9415               2
9654               3
9655               2
9664               3
9665               2
9668               2
9823               3

In [255]:
Tabela.to_csv('Dados.csv')